export const VocabulariesActionTypes = {
    GET_VOCABULARY: '@@vocabulary/GET_VOCABULARIES',
    GET_VOCABULARY_RESPONSE_SUCCESS: '@@vocabulary/GET_VOCABULARIES_RESPONSE_SUCCESS',
    GET_VOCABULARY_RESPONSE_ERROR: '@@vocabulary/GET_VOCABULARIES_RESPONSE_ERROR',
};
